### ISSUE TITLE
[question][documentation] Comparison with OctoPrint

### ISSUE THREAD

**Issue by xaionaro** [leoleovich/3djuggler#12]
Hello.

Just a humble ask. Is it possible to add info about the reasoning behind this project when OctoPrint already exists. This is really nice to see a simple Go daemon to manage 3D printers remotely, but yet :)

For example right now I use OctoPrint at home, but may be it is better to use this instead. What are the advantages of using using 3djuggler instead of OctoPrint? And what are the supposed use cases?

**Comment by yrk-lab** [comment]
We did, in fact, use OctoPrint at the early stages of the project. Over the time, we faced the need for local modifications, and OctoPrint while meant to be extensible with plugin API, had proven to be a burden to maintain. But the main benefit of a compact agent in Go is runtime size: unlike OctoPrint which requires Python runtime, a statically compiled 3djuggler is way more manageable, and allowed us to move away from Mac minis towards a Yocto-based embedded platform.
